In [ ]:
import pandas as pd 
from google.colab import drive
import math

In [ ]:
import numpy as np

In [ ]:
drive.mount('/content/drive')
path = '/content/drive/My Drive/nlp_aug/norm_aug.csv'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv(path)

In [ ]:
df.head(7498)

,Unnamed: 0.1,Unnamed: 0,0,1
0,0,0,0,I can't seem to get my card activated.
1,1,1,0,Help me with the process of activating my card...
2,2,2,0,My new card needs to be activated before I can...
3,3,3,0,Can you assist me in activating my card?
4,4,4,0,What steps do I need to follow to activate my ...
...,...,...,...,...
7493,7493,7493,58,- How quickly will my account be updated after...
7494,7494,7494,58,- What is the maximum amount of money that can...
7495,7495,7495,58,- Can I set up automatic top-ups using my cred...
7496,7496,7496,58,- Is there a limit to how many times per month...
7497,7497,7497,58,How do I add money to my account using a physi...

In [ ]:
df['1']

0                  I can't seem to get my card activated.
1       Help me with the process of activating my card...
2       My new card needs to be activated before I can...
3                Can you assist me in activating my card?
4       What steps do I need to follow to activate my ...
                              ...
9893    It's frustrating when the ATM doesn't accurate...
9894    I prefer using a credit card for international...
9895    I made sure to double-check the current exchan...
9896    There is always some uncertainty surrounding i...
9897    Sometimes it feels like we're at the mercy of ...
Name: 1, Length: 9898, dtype: object

In [ ]:
unique_first_els = []
for i in range(9864):
  if df['1'][i] != 'nan':
    ch = df['1'][i][0]
    if (ch not in unique_first_els):
      unique_first_els.append(ch)

In [ ]:
df['1'][270]

'What is the minimum and maximum amount allowed when topping up through Google Play?'

In [ ]:
unique_first_els

['I',
 'H',
 'M',
 'C',
 'W',
 'T',
 'D',
 'A',
 'P',
 'S',
 'O',
 'F',
 'U',
 'E',
 'L',
 'N',
 'K',
 'Y',
 'R',
 'V',
 'G']

In [ ]:
df['1'] = df['1'].astype(str)

In [ ]:
df['1'] = df['1'].apply(delete_numeration)

In [ ]:
df = df.dropna()

In [ ]:
df = df.reset_index(drop=True)

In [ ]:
def delete_numeration(string):
  string.strip()
  if (string[0].isdigit() == True or string[0] == '-'):
    if (string[1].isdigit() == True):
      return string[3:].strip()
    return string[2:].strip()
  else:
    return string.strip()

In [ ]:
df.rename(columns={'0': 'class', '1': 'text'}, inplace=True)

In [ ]:
df

      class                                               text
0         0             I can't seem to get my card activated.
1         0  Help me with the process of activating my card...
2         0  My new card needs to be activated before I can...
3         0           Can you assist me in activating my card?
4         0  What steps do I need to follow to activate my ...
...     ...                                                ...
9859     76  It's frustrating when the ATM doesn't accurate...
9860     76  I prefer using a credit card for international...
9861     76  I made sure to double-check the current exchan...
9862     76  There is always some uncertainty surrounding i...
9863     76  Sometimes it feels like we're at the mercy of ...

[9864 rows x 2 columns]

In [ ]:
with open(path, 'w', encoding = 'utf-8-sig') as f:
  df.to_csv(f)